### ISSUE TITLE
Update sources reflect that the student's "mark yourself as present" step was removed from the hackathon

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/batch4-students#36]
https://docs.google.com/document/d/1b9GVfNoCj-VzL2xWnqJuFg3JMEpeBw_fXhkUirItPUM/edit

**Comment by buedaswag** [comment]
need to remove marking attendence step (which was deprecated) from the hackathon google docs:

* in the instructors repo
    * ![image](https://user-images.githubusercontent.com/33937027/89119369-00205500-d4a6-11ea-94ca-030c0acef9a1.png)
    * https://docs.google.com/document/d/1iuZsxN0i6y3vJWGTDMMljxPAmZb-sZyBkjbBuSboyL4/edit#heading=h.ejeq9rg4kyaz
* in the students repo
    * ![image](https://user-images.githubusercontent.com/33937027/89119386-1f1ee700-d4a6-11ea-8f10-9e9efd59d826.png)
    * https://docs.google.com/document/d/1b9GVfNoCj-VzL2xWnqJuFg3JMEpeBw_fXhkUirItPUM/edit#

**Comment by hcastilho** [comment]
Closing as batch4 is comming to its  end
